services:
  frontend:
    build:
      context: ./TestAngular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - myapp-network
  
  
  backend:
    build:
      context: ./TestDotNetCore
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - myapp-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;DataBase=MyAppDataBase;User=sa;Password=Password_123#;TrustServerCertificate=True

  database:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
    networks:
      - myapp-network
    user: root

networks:
  myapp-network:
    driver: bridge
    
volumes:
  sqlserver-data:
    driver: local